resource_types:
  - name: bitbucket-build-status
    type: registry-image
    source:
      repository: mgbi/bitbucket-build-status-resource

resources:
- name: stage-branch
  type: git
  source:
    uri: ((repo-uri))
    branch: release/prod
    private_key: ((private-repo-key))
    
- name: build-status
  type: bitbucket-build-status
  source:
    driver: Bitbucket Cloud
    client_id: ((bitbucket-client-id))
    client_secret: ((bitbucket-client-secret))
    repository: ((bitbucket-repository))
    
jobs:
- name: deploy-stage-env
  serial: true
  build_logs_to_retain: 10
  plan:
#  - get: stage-branch
#    trigger: true
#    passed: [build-prod-images]
  - put: build-status
    params:
      build_status: INPROGRESS
      repository: stage-branch
      description_file: stage-branch/build_descriptions/deploy-stage-env.txt
  - task: deploy
    input_mapping:
      source: stage-branch
    file: stage-branch/tasks/rancher-deploy.yml
    params:
      COMPOSE_PROJECT_NAME: ((compose-project-name))
      RANCHER_URL: ((stage-rancher-url))
      RANCHER_ACCESS_KEY: ((stage-rancher-access-key))
      RANCHER_SECRET_KEY: ((stage-rancher-secret-key))
#      SECRETS_FROM_ENV_FILES: 1
    timeout: 5m
    attempts: 3 # for Client.Timeout exceeded while awaiting headers
  - in_parallel:
    - task: init-mongo-rs
      file: stage-branch/tasks/rancher-init-mongo-rs.yml
      params:
        RANCHER_URL: ((stage-rancher-url))
        RANCHER_ACCESS_KEY: ((stage-rancher-access-key))
        RANCHER_SECRET_KEY: ((stage-rancher-secret-key))
        RANCHER_CONTAINER_NAME: ((rancher-mongo-container-name))
      timeout: 1m
    # add more initial tasks here, like this:
    #- task: import-extra-data
    #  file: stage-branch/tasks/rancher-import-extra-data.yml
    #  params:
    #    RANCHER_URL: ((stage-rancher-url))
    #    RANCHER_ACCESS_KEY: ((stage-rancher-access-key))
    #    RANCHER_SECRET_KEY: ((stage-rancher-secret-key))
    #    RANCHER_CONTAINER_NAME: ((rancher-main-container-name))
    #    EXTRA_DATA_CSV_URL: ((extra-data-csv-url))
    #    EXTRA_DATA_DIR: /media/extra_data
    #  timeout: 15m
  on_success:
    put: build-status
    params:
      build_status: SUCCESSFUL
      repository: stage-branch
      description_file: stage-branch/build_descriptions/deploy-stage-env.txt
  on_failure:
    put: build-status
    params:
      build_status: FAILED
      repository: stage-branch
      description_file: stage-branch/build_descriptions/deploy-stage-env.txt
